language: ruby
os:
  - osx
before_install:
  - brew update
  - brew install ansible
  - ansible --version
  - ansible -m setup localhost
  - cp .default-gems $HOME/
script:
  - ansible-playbook -vv main.yml -i hosts
  - rake
notifications:
    slack: shimi-rsslack:bUoxLktUdcotH8rYgMyCcTJR
