language: ruby
os:
  - osx
before_install:
  - brew update
  - brew install ansible
  - ansible --version
  - ansible -m setup localhost
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
  - cp .default-gems $HOME/
script:
  - ansible-playbook -vv main.yml -i hosts
  # - rake
  - inspec exec spec/asdf_spec.rb
notifications:
    slack: shimi-rsslack:bUoxLktUdcotH8rYgMyCcTJR
