language: ruby
os:
  - osx
before_install:
  - brew update
  - brew install ansible
  - ansible --version
  - ansible -m setup localhost
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
  - cp .default-gems $HOME/
script:
  - ansible-playbook -vv main.yml -i inventory
  - bash -lc 'which gem'
  - bash -lc 'which pip'
  - rake inspec:default
notifications:
    slack: shimi-rsslack:bUoxLktUdcotH8rYgMyCcTJR
