---
- name: "install asdf"
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "~/.asdf"
    # version: "{{ asdf_version }}"
  # become_user: "{{ asdf_user }}"

- name: insert/update asdf shell in bash_profile
  blockinfile:
    path: ~/.bash_profile
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash
