---
- name: Install plugins
  shell: /bin/bash -lc "asdf plugin-add {{ item }}"
  with_items:
    - python
    - ruby
    - go

- name: List plugins
  shell: /bin/bash -lc "asdf list-all {{ item }}"
  register: result
  with_items:
    - python
    - ruby
    - go
- debug: var=item.stdout_lines
  with_items: '{{ result.results }}'

- name: Install plugins
  shell: /bin/bash -lc "asdf global {{ item.name }} {{ item.version }}"
  with_items:
    - { name: python, version: 3.7.1 }
    - { name: ruby, version: 2.5.3 }
    - { name: go, version: 1.11 }
