---
# - name: Upgrade gem
#   shell: /bin/bash -lc "gem update --system"
# - name: Recreate
#   shell: /bin/bash -lc "gem pristine --all"
# - name: Upgrade bundler
#   shell: /bin/bash -lc "gem update bundler"

- name: Install gem packages
  gem:
    name: "{{ item }}"
    executable: "{{ ansible_env.HOME }}/.asdf/shims/gem"
    user_install: False
  with_items:
    - travis
    - rake
    - bundler

- name: install pip packages
  pip:
    name: "{{ item }}"
    executable: "{{ ansible_env.HOME }}/.asdf/shims/pip"
    state: latest
  with_items:
    - pip
    - awscli
    - molecule
    - docker-py
