---
- stat: 
    path: "{{ ansible_env.HOME }}/.asdf/asdf.sh"
  register: is_file

- name: "install asdf"
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "~/.asdf"
  when: not is_file.stat.exists

- name: insert/update asdf shell in bash_profile
  blockinfile:
    path: ~/.bash_profile
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash
  when: not is_file.stat.exists
